services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  notice:
    build: ./notice
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq